apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.106
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
    protocol: TCP
  - name: pasv
    port: 30021
    targetPort: 30021
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
  labels:
    app: ftps
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
